[package]
name = "proxy-gun"
version = "0.1.0"
authors = ["a <360d@pm.me>"]
edition = "2018"

[dependencies]
bytes = "0.5"
log = "0.4.8"

[dependencies.async-std]
version = "1.4.0"
features = ["attributes"]
